version: '3.6'

services:
  db:
    image: mysql:5.7
    container_name: megahack-db
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - megahack-dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=megahack
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

  api:
    build: .
    container_name: megahack-api
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app

volumes:
  megahack-dbdata:
    external: true
